apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mkurowskiug/tc-frontend:latest
        ports:
          - containerPort: 3000
        envFrom:
          - secretRef:
              name: frontend-secrets
___

apiVersion: v1
kind: Service
metadata:
  name: myapp
type: loadbalancer
spec:
  selector:
    app: myapp
  ports:
  - port: <Port>
    targetPort: <Target Port>

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
type: Opaque
data:
  AUTH_KEYCLOAK_SECRET: bVBGWVVxOUpzcDRCU2NBMW85cjRwbkE0eXlKOHRReEU=
  AUTH_KEYCLOAK_ID: dG9kb2xpc3QtbmV4dGpz
  AUTH_KEYCLOAK_ISSUER: aHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9zaW1wbGVUb2RvTGlzdA==
  AUTH_URL: aHR0cDovL2xvY2FsaG9zdDozMDAw
  AUTH_SECRET: czkvS1pZWStjWk9vNVcwak9UK3NoTDF2dHhWQjVqMnp5eGVWYXdLUUw4bz0=
  AUTH_TOKEN_ENDPOINT: aHR0cDovL2tleWNsb2FrOjgwODAvcmVhbG1zL3NpbXBsZVRvZG9MaXN0L3Byb3RvY29sL29wZW5pZC1jb25uZWN0L3Rva2Vu
  NEXT_PUBLIC_BACKEND_URL: aHR0cDovL2xvY2FsaG9zdDo1MDAw
  AUTH_KEYCLOAK_AUTH_URL: aHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9zaW1wbGVUb2RvTGlzdC9wcm90b2NvbC9vcGVuaWQtY29ubmVjdC9hdXRo
  AUTH_TRUST_HOST: dHJ1ZQ==
  AUTH_WELL_KNOWN: aHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy9zaW1wbGVUb2RvTGlzdC8ud2VsbC1rbm93bi9vcGVuaWQtY29uZmlndXJhdGlvbg==
